Refractor plugin uninstallation backend
SteamDeckHomebrew/decky-loader pull request #111
Opened 2022-07-06 05:43 UTC by botatooo

Use server methods instead of directly hitting up the browser endpoint, makes it less janky.

2022-07-06 13:51 UTC, AAGaming00 requested changes
Maybe do this for the install method too?

2022-07-06 13:55 UTC, botatooo commented
Plugin installation already utilizes server methods, no?

2022-07-06 13:56 UTC, botatooo commented
Oh, I see what you mean.

2022-07-06 21:53 UTC, AAGaming00 commented
@WerWolv opinions on the formatting applied here?

2022-07-09 05:08 UTC, AAGaming00 approved these changes
Code-wise LGTM, still waiting on Wolv's opinion on the formatter. Will test soon.

2022-07-11 07:06 UTC, WerWolv commented
Code-wise everything looks alright to me as well.

Formatting-wise, it partially feels like you just used an auto formatter that only allows a certain number of characters per line.
For me this makes it somewhat harder to read. Array indexes in my opinion should never be split up onto more than one lines. If the index value is too long, I'd write the result to a variable and then use that to index.
For function calls, if there are way too many parameters, I'll usually put each parameter on its own line and not just put the entire list of parameters on the next line.

2022-07-11 07:14 UTC, botatooo commented
I'll take a note and do what I can in the next commit.

2022-07-11 07:46 UTC, botatooo commented
> Code-wise everything looks alright to me as well.
> 
> Formatting-wise, it partially feels like you just used an auto formatter that only allows a certain number of characters per line. For me this makes it somewhat harder to read. Array indexes in my opinion should never be split up onto more than one lines. If the index value is too long, I'd write the result to a variable and then use that to index. For function calls, if there are way too many parameters, I'll usually put each parameter on its own line and not just put the entire list of parameters on the next line.

Did what I could manually, if it needs changes i will revisit it with a proper editor and not GitHub mobile.

2022-07-11 23:37 UTC, TrainDoctor approved these changes
This is good for merging.

2022-07-12 00:40 UTC, Gerrickjohnson approved these changes

2022-07-26 14:39 UTC, AAGaming00 commented
This needs to be adapted for recent changes.

2022-07-26 17:43 UTC, botatooo commented
> This needs to be adapted for recent changes.

Conflicts have been resolved.

2022-07-27 22:39 UTC, TrainDoctor requested changes
Tested it on my deck via manual file replacement and works like a charm.
Did encounter an issue where the uninstall modal shows up but neither confirm or cancel are selected. Hitting the "A" button to confirm as if confirm was selected seems to press the uninstall button behind the modal and uninstall the plugin as if confirm was selected.
Once this issue is resolved, this will be good to merge.

2022-07-30 15:30 UTC, TrainDoctor approved these changes
With recent discoveries testing @pastaq's changes the uninstall prompt issues appear to be in the main codebase so we'll look into sorting that ourselves. I'll need another approving review before this can fully go ahead.

2022-07-30 18:22 UTC, AAGaming00 approved these changes
LGTM, will test when I have time.

2022-08-16 00:46 UTC, AAGaming00 approved these changes

2022-08-26 05:29 UTC, AAGaming00 approved these changes

2022-08-26 14:23 UTC, TrainDoctor requested changes
A few line removals that need to have their removal checked

2022-08-26 14:23 UTC, TrainDoctor commented on backend/main.py
> -             self.cors.add(route)
Why where these lines removed?

2022-08-26 14:23 UTC, TrainDoctor commented on backend/utilities.py
> -                return {
Why where these lines removed?

2022-08-26 14:26 UTC, TrainDoctor commented
> A few line removals that need to have their removal checked

Also a few errors relating to indentation and so on causing the build CI to fail.

2022-08-26 15:49 UTC, AAGaming00 approved these changes
Tested locally, everything seems to work.

2022-08-27 04:01 UTC, merged