allow hand-sorting plugins
SteamDeckHomebrew/decky-loader pull request #277
Opened 2022-12-11 14:32 UTC by phryneas

This would solve #226.

As I was almost done with that, @Tormak9970 mentioned that they had their own implementation to list sorting, so maybe that might be preferrable over this - but either way, maybe some other code from this PR might be salvageable :)

[Scrrenshot of the orderable list by Tormak9970](https://github.com/Tormak9970/portfolio-site-v2/blob/main/public/img/projs/Bash%20Shortcuts%20-%20Manage%20View.png)

[Screenshot of my solution](https://steamcommunity.com/sharedfiles/filedetails/?id=2900472013)

I went for the approach of having a sorted array of plugin names and keeping that in a setting.  
This required me to add an `EventTarget` to the `useSettings` hook so that updating a setting in one screen will synchronize to all other screens. Granted, this could also be done with an additional Context, but seems to work very nicely and imitates a pattern that is already used elsewhere in Decky.

2022-12-11 16:25 UTC, JediRhymeTrix commented
Quick question, does this prevent newly updated plugins from always migrating to the bottom?

2022-12-11 16:43 UTC, AAGaming00 requested changes

2022-12-11 16:54 UTC, phryneas commented on frontend/src/utils/hooks/useSetting.ts
> +      if (event instanceof CustomEvent) {
It is an EventListener for all events of `type` "`key`"  (see `settingUpdates.addEventListener(key, listener)` )  below. So each setting has their own event type and they are separated that way.

2022-12-11 16:56 UTC, phryneas commented
> Quick question, does this prevent newly updated plugins from always migrating to the bottom?

New plugins land at the bottom and then you can sort them to a specific position, where they will stay. They have to start somewhere though.

2022-12-11 17:02 UTC, AAGaming00 commented on frontend/src/utils/hooks/useSetting.ts
> +      if (event instanceof CustomEvent) {
Ah

2022-12-11 20:26 UTC, AAGaming00 commented
On hold until Tormak's reorderable component is merged.

2023-02-02 01:15 UTC, TrainDoctor commented
Closed in favor of an upcoming solution being PRed into DFL.

2023-02-02 01:15 UTC, closed without merging