Added Simplified Chinese support
SteamDeckHomebrew/decky-loader pull request #438
Opened 2023-05-03 03:09 UTC by seanzhang98

2023-05-04 21:06 UTC, PunkyBust commented
Hello,
Same here but for french, I don't find this file on my deck.
And have no hand on github side, so how can we add our localization please ? fr-FR needed on my side.
Thanks  :)

2023-05-04 21:13 UTC, TrainDoctor commented
We are currently setting up a weblate to help with translation @PunkyBust. We will file an issue and pin it for future people who want to contribute translations.

2023-05-04 21:19 UTC, PunkyBust commented
OK great, understand better now. Happy to contribute if I can help for french translation

2023-05-05 08:53 UTC, RodoMa92 requested changes
See my comment below.

2023-05-05 08:53 UTC, RodoMa92 commented on backend/locales/zh-CN.json
> +      "checking": "'检查中",
The initial ' after " was a typo in the english translation, please remove that.

2023-05-05 09:27 UTC, seanzhang98 commented
Updated the config file and the translation as well.

2023-05-05 09:39 UTC, RodoMa92 commented
Just to be sure that there is no translation strings missing for the framework, can you please try to run the activity extract text (Control + Shift + P, insert activity enter, insert extracttext enter) and eventually complete the new strings added to the json file? After that this should be good to merge to me.

2023-05-05 11:46 UTC, seanzhang98 commented
Not sure how to run the activity extract text on my set up. Tried Control + Shift + P but nothing happened.

2023-05-05 11:55 UTC, RodoMa92 commented
Here you can find a guide on tasks (my translation in my language is different, sorry) https://code.visualstudio.com/docs/editor/tasks

2023-05-05 13:20 UTC, RodoMa92 commented
Just tested personally, it's fine as keys goes. It can go in now.

2023-05-17 08:47 UTC, RodoMa92 commented
I've manually added your translation to the weblate instance that the team brought up recently, it should be in shortly in the loader itself. You can find it here if you want to add/correct any mistake made by my copy and paste :P : https://weblate.werwolv.net/projects/decky/decky/

2023-05-17 21:46 UTC, closed without merging