add cef console button to developer settings
SteamDeckHomebrew/decky-loader pull request #441
Opened 2023-05-04 02:59 UTC by Witherking25

2023-05-04 03:00 UTC, Witherking25 commented
oop my ide did a bad job with the commit username lol

2023-05-04 16:40 UTC, PartyWumpus commented
Works well, although it would probably be more convinient if it went directly to the `SharedJSContext` page, as no other pages would actually be useful as far as i can tell.
From the python side, a way of getting a link directly there would be `(await get_tab('SharedJSContext')).id` (which returns a value along the lines of `E88A4C68268596E8826CB5C08DA8F5FE`). 
Then in ts, run `NavigateToExternalWeb("localhost:8080/devtools/inspector.html?ws=localhost:8080/devtools/page/"+id)`
I did find tab.ws_url, but it returns `ws://localho...` not `ws=localho..`.

Okay I'm just going to try do this myself at this point. If it fails then I guess it can fall back to localhost:8080.

Clip of it working just to be sure:

https://user-images.githubusercontent.com/48649272/236269281-a96f2446-13f2-491e-9c5a-206fac6663cd.mp4

2023-05-04 17:01 UTC, Witherking25 commented
Oh neat, a pr to a pr? Lol

2023-05-04 17:25 UTC, PartyWumpus commented
I guess so lol. Can't edit this directly so I'll make a PR.

2023-05-04 17:34 UTC, Witherking25 commented
yea having it directly open the console would be preferable

2023-05-04 17:36 UTC, Witherking25 commented
also need italian translations for the new ui elements, but probably let the guy that did the i18n stuff do that as i believe he made the ones for the rest of the ui if i remember correctly

2023-05-04 17:41 UTC, PartyWumpus commented
I feel a little stupid right now, but your repo is protected so I can't directly edit it (unlike most PRs), and I can't make a fork of your fork without deleting my existing one (which I can't do). I guess I could make a fork under the steamdeckhomebrew team, but that seems silly.

2023-05-04 17:42 UTC, Witherking25 commented
i can give you write access if you want

2023-05-04 17:43 UTC, Witherking25 commented
wait would this fix?
Disable branch protection rules

2023-05-04 17:43 UTC, PartyWumpus commented
Yeah that would probably work, sounds good.

2023-05-04 17:44 UTC, Witherking25 commented
ok try now

2023-05-04 17:49 UTC, Witherking25 commented
here i just added you to the repo so you can just push to it lol

2023-05-04 17:53 UTC, Witherking25 commented
nice

2023-05-04 17:57 UTC, PartyWumpus commented
Hopefully someone else has the time to test this, because I don't know if I can test my own code lol.
I'll still give it a test once it's finished building though.

2023-05-04 18:13 UTC, Witherking25 commented
works great for me

2023-05-04 18:36 UTC, PartyWumpus commented
did you just accidentally overwrite your fork?

2023-05-04 18:51 UTC, PartyWumpus commented
It's working well on my PC and my deck

https://user-images.githubusercontent.com/48649272/236298266-95ff1e63-8250-4ef5-94af-0626258a3fc4.mp4

2023-05-31 17:29 UTC, JohnnyCrazy requested changes
Just 2 small things, otherwise LGTM

2023-06-01 18:04 UTC, Witherking25 commented on frontend/src/components/settings/pages/developer/index.tsx
> +              console.log(res.result);
oops

2023-06-01 18:04 UTC, Witherking25 commented on frontend/src/components/settings/pages/developer/index.tsx
> +            let res = (await window.DeckyPluginLoader.callServerMethod('get_tab_id', { "name": "SharedJSContext" }));
i like being verbose with my parentheses, but i can remove them if you like :)

2023-06-01 18:10 UTC, TrainDoctor approved these changes
Tested on my deck, works good. Once Johnny approves this will be good for merge.

2023-06-01 22:42 UTC, JohnnyCrazy approved these changes

2023-06-01 23:01 UTC, merged