Add zh-TW translation
SteamDeckHomebrew/decky-loader pull request #442
Opened 2023-05-04 05:21 UTC by david082321

2023-05-04 12:48 UTC, RodoMa92 commented
Can you please add your language in this [line](https://github.com/SteamDeckHomebrew/decky-loader/blob/main/frontend/i18next-parser.config.mjs#L39), so it will be automatically exported each time new strings are added?

2023-05-05 08:50 UTC, RodoMa92 requested changes
See my comment in the code below.

2023-05-05 08:50 UTC, RodoMa92 commented on backend/locales/zh-TW.json
> +      "checking": "'正在檢查",
The ' after the " was a typo in my english translation, after that is removed it looks good to merge to me.

2023-05-11 06:12 UTC, RodoMa92 approved these changes
LGTM

2023-05-17 09:11 UTC, RodoMa92 commented
Merged it myself in the weblate instance that should almost ready to help translation, you can find it here if you need to fix my mistakes during copy and paste :P : https://weblate.werwolv.net/projects/decky/decky/

I think we can close this.

2023-05-18 10:01 UTC, closed without merging

2023-05-18 12:38 UTC, david082321 commented
> Merged it myself in the weblate instance that should almost ready to help translation, you can find it here if you need to fix my mistakes during copy and paste :P : https://weblate.werwolv.net/projects/decky/decky/
> 
> I think we can close this.

I can't translate these two strings:
1. https://weblate.werwolv.net/translate/decky/decky/zh_Hant/?checksum=e89b0404c593bfe0
2. https://weblate.werwolv.net/translate/decky/decky/zh_Hant/?checksum=52c080da9da21b4d