Add Plugin.uninstall callback support
SteamDeckHomebrew/decky-loader pull request #555
Opened 2023-11-01 18:55 UTC by wheaney

https://github.com/SteamDeckHomebrew/decky-loader/issues/536

Please tick as appropriate:
- [x] I have tested this code on a steam deck or on a PC
- [x] My changes generate no new errors/warnings
- [x] This is a bugfix/hotfix
- [ ] This is a new feature

If you're wanting to update a translation or add a new one, please use the weblate page: https://weblate.werwolv.net/projects/decky/

# Description

This fixes issue: #536

2023-11-02 16:00 UTC, wheaney commented
Here is the PR for the plugin template update: https://github.com/SteamDeckHomebrew/decky-plugin-template/pull/34

2023-11-07 23:17 UTC, wheaney commented
@TrainDoctor what's next for this?

2023-11-08 00:11 UTC, TrainDoctor commented
> @TrainDoctor what's next for this?

Needs testing. @SteamDeckHomebrew/decky-testers please give this a shot and let me know if you encounter any issues.

2023-12-16 01:47 UTC, TrainDoctor commented
@wheaney apologies for the delay. I finally have time to give this a whirl tomorrow. If you can rebase it to latest main that'd make it much easier for me to test.

2023-12-16 04:55 UTC, wheaney commented
I'm not sure what was going on with that first merge, but I think it's all sync'ed up now.

2024-02-06 23:28 UTC, JohnnyCrazy requested changes
I think this is a good addition - can you remove the empty file and rebase? Will do some testing the next days.

2024-02-06 23:28 UTC, JohnnyCrazy commented on contrib/deck.sh
Empty file - should be removed

2024-02-09 01:14 UTC, TrainDoctor commented
> I think this is a good addition - can you remove the empty file and rebase? Will do some testing the next days.

@wheaney once this change is made I can pretty easily merge this. Thanks.

2024-02-26 22:55 UTC, wheaney commented
The commit history here was confusing me, so I just rebased, removed the empty file, and force pushed.

2024-03-13 22:59 UTC, JohnnyCrazy commented
Mergin, thanks for this @wheaney !

2024-03-13 22:59 UTC, merged